// Preset parameter sets for ParticleSystem. Every field is optional — the
// system deep-merges a preset over its defaults, then user options over that.
// life: [min, max] seconds; a negative min means immortal (life = -1).

export const PARTICLE_PRESETS = {
    flying: {
        mode: 'sim',
        emitter: {
            rate: 8000,
            position: [0, 0, 0],
            radius: 1.5,
            direction: [0, 0, 0],
            spread: 1,
            speed: [0.05, 0.3],
            life: [2, 5],
        },
        forces: {
            gravity: [0, 0, 0],
            wind: [0, 0, 0],
            drag: 1.2,
            curlAmp: 1.4,
            curlFreq: 0.45,
            attractor: [0, 0, 0],
            attractorStrength: 0.6,
        },
        appearance: {
            size: 0.02,
            blending: 'additive',
            billboard: 'camera',
            stretch: 0,
            opacity: 0.8,
            softness: 1,
            sizeKnots: [0, 1, 1, 0],
            alphaKnots: [0, 1, 1, 0],
            colors: [
                [0.4, 0.7, 1.0],
                [0.6, 0.8, 1.0],
                [1.0, 0.7, 0.9],
                [1.0, 0.4, 0.6],
            ],
        },
    },

    snowing: {
        mode: 'sim',
        emitter: {
            rate: 3000,
            position: [0, 4, 0],
            box: [6, 0.1, 6],
            direction: [0, -1, 0],
            spread: 0.1,
            speed: [0.4, 0.9],
            life: [8, 14],
        },
        forces: {
            gravity: [0, -0.3, 0],
            wind: [0.25, 0, 0.1],
            drag: 0.6,
            curlAmp: 0.5,
            curlFreq: 0.5,
            attractorStrength: 0,
        },
        appearance: {
            size: 0.03,
            blending: 'premultiplied',
            billboard: 'camera',
            stretch: 0,
            opacity: 0.9,
            softness: 0.8,
            sizeKnots: [0.6, 1, 1, 0.8],
            alphaKnots: [0, 1, 1, 0],
            colors: [
                [0.9, 0.93, 1.0],
                [0.95, 0.97, 1.0],
                [0.95, 0.97, 1.0],
                [0.85, 0.9, 1.0],
            ],
        },
    },

    blowing: {
        mode: 'sim',
        emitter: {
            rate: 6000,
            position: [-5, 0.5, 0],
            box: [0.2, 1.5, 3],
            direction: [1, 0.05, 0],
            spread: 0.15,
            speed: [2, 5],
            life: [1.5, 3.5],
        },
        forces: {
            gravity: [0, -0.2, 0],
            wind: [2.5, 0, 0],
            drag: 0.5,
            curlAmp: 2.2,
            curlFreq: 0.7,
            attractorStrength: 0,
        },
        appearance: {
            size: 0.015,
            blending: 'additive',
            billboard: 'stretched',
            stretch: 0.15,
            opacity: 0.5,
            softness: 1,
            sizeKnots: [0.4, 1, 1, 0.3],
            alphaKnots: [0, 0.8, 0.8, 0],
            colors: [
                [0.7, 0.8, 0.9],
                [0.8, 0.85, 0.9],
                [0.7, 0.75, 0.85],
                [0.5, 0.55, 0.7],
            ],
        },
    },

    fountain: {
        mode: 'sim',
        emitter: {
            rate: 12000,
            position: [0, -1, 0],
            radius: 0.08,
            direction: [0, 1, 0],
            spread: 0.12,
            speed: [4, 6],
            life: [1.2, 2.2],
        },
        forces: {
            gravity: [0, -5, 0],
            wind: [0, 0, 0],
            drag: 0.15,
            curlAmp: 0.4,
            curlFreq: 1.2,
            attractorStrength: 0,
        },
        appearance: {
            size: 0.02,
            blending: 'premultiplied',
            billboard: 'stretched',
            stretch: 0.12,
            opacity: 0.75,
            softness: 0.9,
            sizeKnots: [0.5, 1, 1, 0.7],
            alphaKnots: [0.9, 1, 0.7, 0],
            colors: [
                [0.55, 0.75, 1.0],
                [0.6, 0.8, 1.0],
                [0.7, 0.85, 1.0],
                [0.8, 0.9, 1.0],
            ],
        },
    },

    embers: {
        mode: 'sim',
        emitter: {
            rate: 900,
            position: [0, -1.2, 0],
            box: [1.6, 0.1, 1.6],
            direction: [0, 1, 0],
            spread: 0.3,
            speed: [0.3, 1.1],
            life: [2, 4.5],
        },
        forces: {
            gravity: [0, 0.5, 0],
            wind: [0.15, 0, 0],
            drag: 0.4,
            curlAmp: 1.1,
            curlFreq: 0.9,
            attractorStrength: 0,
        },
        appearance: {
            size: 0.02,
            blending: 'additive',
            billboard: 'camera',
            stretch: 0,
            opacity: 1,
            softness: 1,
            sizeKnots: [1, 0.8, 0.5, 0],
            alphaKnots: [0, 1, 0.6, 0],
            colors: [
                [1.0, 0.9, 0.4],
                [1.0, 0.6, 0.15],
                [0.9, 0.3, 0.05],
                [0.3, 0.05, 0.01],
            ],
        },
    },

    'immortal-field': {
        mode: 'sim',
        emitter: {
            rate: 0, // filled by an initial burst; immortal particles never die
            burst: 100000,
            position: [0, 0, 0],
            radius: 1.2,
            direction: [0, 0, 0],
            spread: 1,
            speed: [0, 0.05],
            life: [-1, -1],
        },
        forces: {
            gravity: [0, 0, 0],
            wind: [0, 0, 0],
            drag: 1.4,
            curlAmp: 0.6,
            curlFreq: 0.5,
            attractor: [0, 0, 0],
            attractorStrength: 0.9,
        },
        appearance: {
            size: 0.012,
            blending: 'additive',
            billboard: 'camera',
            stretch: 0,
            opacity: 0.55,
            softness: 1,
            sizeKnots: [1, 1, 1, 1],
            alphaKnots: [1, 1, 1, 1],
            colors: [
                [0.5, 0.7, 1.0],
                [0.5, 0.7, 1.0],
                [0.5, 0.7, 1.0],
                [0.5, 0.7, 1.0],
            ],
        },
    },

    flock: {
        mode: 'boids',
        emitter: {
            rate: 0,
            burst: 4000,
            position: [0, 0, 0],
            radius: 2,
            direction: [0, 0, 0],
            spread: 1,
            speed: [0.8, 1.6],
            life: [-1, -1],
        },
        forces: {
            gravity: [0, 0, 0],
            wind: [0, 0, 0],
            drag: 0,
            curlAmp: 0,
            curlFreq: 0.5,
            attractor: [0, 0, 0],
            attractorStrength: 1.4, // gentle pull home so the flock stays in view
        },
        boids: {
            separation: 0.08,
            alignment: 1.2,
            cohesion: 0.8,
            neighborRadius: 0.5,
            maxSpeed: 2.2,
            maxForce: 6,
            extent: 16, // grid world size (32 cells * cellSize), centered on origin
        },
        appearance: {
            size: 0.035,
            blending: 'premultiplied',
            billboard: 'stretched',
            stretch: 0.1,
            opacity: 1,
            softness: 0.4,
            sizeKnots: [1, 1, 1, 1],
            alphaKnots: [1, 1, 1, 1],
            colors: [
                [0.15, 0.15, 0.18],
                [0.2, 0.2, 0.25],
                [0.25, 0.25, 0.3],
                [0.15, 0.15, 0.18],
            ],
        },
    },
};
